<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class KabupatenSeed extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {

        /* `das`.`wilayah_kabupaten` */
        $wilayah_kabupaten = [
            ['id' => '1', 'provinsi_id' => '1', 'name' => 'Kabupaten Aceh Selatan', 'ibukota' => 'Tapak Tuan', 'k_bsni' => 'TTN'],
            ['id' => '2', 'provinsi_id' => '1', 'name' => 'Kabupaten Aceh Tenggara', 'ibukota' => 'Kutacane', 'k_bsni' => 'KTN'],
            ['id' => '3', 'provinsi_id' => '1', 'name' => 'Kabupaten Aceh Timur', 'ibukota' => 'Langsa', 'k_bsni' => 'LGS'],
            ['id' => '4', 'provinsi_id' => '1', 'name' => 'Kabupaten Aceh Tengah', 'ibukota' => 'Takengon', 'k_bsni' => 'TKN'],
            ['id' => '5', 'provinsi_id' => '1', 'name' => 'Kabupaten Aceh Barat', 'ibukota' => 'Meulaboh', 'k_bsni' => 'MBO'],
            ['id' => '6', 'provinsi_id' => '1', 'name' => 'Kabupaten Aceh Besar', 'ibukota' => 'Jantho', 'k_bsni' => 'JTH'],
            ['id' => '7', 'provinsi_id' => '1', 'name' => 'Kabupaten Pidie', 'ibukota' => 'Sigli', 'k_bsni' => 'SGI'],
            ['id' => '8', 'provinsi_id' => '1', 'name' => 'Kabupaten Aceh Utara', 'ibukota' => 'Lhoksukon', 'k_bsni' => 'LSK'],
            ['id' => '9', 'provinsi_id' => '1', 'name' => 'Kabupaten Simeulue', 'ibukota' => 'Sinabang', 'k_bsni' => 'SNB'],
            ['id' => '10', 'provinsi_id' => '1', 'name' => 'Kabupaten Aceh Singkil', 'ibukota' => 'Singkil', 'k_bsni' => 'SKL'],
            ['id' => '11', 'provinsi_id' => '1', 'name' => 'Kabupaten Bireuen', 'ibukota' => 'Bireuen', 'k_bsni' => 'BIR'],
            ['id' => '12', 'provinsi_id' => '1', 'name' => 'Kabupaten Aceh Barat Daya', 'ibukota' => 'Blangpidie', 'k_bsni' => 'BPD'],
            ['id' => '13', 'provinsi_id' => '1', 'name' => 'Kabupaten Gayo Lues', 'ibukota' => 'Blangkejeren', 'k_bsni' => 'BKJ'],
            ['id' => '14', 'provinsi_id' => '1', 'name' => 'Kabupaten Aceh Jaya', 'ibukota' => 'Calang', 'k_bsni' => 'CAG'],
            ['id' => '15', 'provinsi_id' => '1', 'name' => 'Kabupaten Nagan Raya', 'ibukota' => 'Suka Makmue', 'k_bsni' => 'SKM'],
            ['id' => '16', 'provinsi_id' => '1', 'name' => 'Kabupaten Aceh Tamiang', 'ibukota' => 'Karang Baru', 'k_bsni' => 'KRB'],
            ['id' => '17', 'provinsi_id' => '1', 'name' => 'Kabupaten Bener Meriah', 'ibukota' => 'Simpang Tiga Redelong', 'k_bsni' => 'STR'],
            ['id' => '18', 'provinsi_id' => '1', 'name' => 'Kabupaten Pidie Jaya', 'ibukota' => 'Meureundu', 'k_bsni' => 'MRN'],
            ['id' => '19', 'provinsi_id' => '1', 'name' => 'Kota Banda Aceh', 'ibukota' => 'Banda Aceh', 'k_bsni' => 'BNA'],
            ['id' => '20', 'provinsi_id' => '1', 'name' => 'Kota Sabang', 'ibukota' => 'Sabang', 'k_bsni' => 'SAB'],
            ['id' => '21', 'provinsi_id' => '1', 'name' => 'Kota Lhokseumawe', 'ibukota' => 'Lhokseumawe', 'k_bsni' => 'LSM'],
            ['id' => '22', 'provinsi_id' => '1', 'name' => 'Kota Langsa', 'ibukota' => 'Langsa', 'k_bsni' => 'LGS'],
            ['id' => '23', 'provinsi_id' => '1', 'name' => 'Kota Subulussalam', 'ibukota' => 'Subulussalam', 'k_bsni' => 'SUS'],
            ['id' => '24', 'provinsi_id' => '2', 'name' => 'Kabupaten Tapanuli Tengah', 'ibukota' => 'Sibolga', 'k_bsni' => 'SBG'],
            ['id' => '25', 'provinsi_id' => '2', 'name' => 'Kabupaten Tapanuli Utara', 'ibukota' => 'Tarutung', 'k_bsni' => 'TRT'],
            ['id' => '26', 'provinsi_id' => '2', 'name' => 'Kabupaten Tapanuli Selatan', 'ibukota' => 'Padang Sidempuan', 'k_bsni' => 'PSP'],
            ['id' => '27', 'provinsi_id' => '2', 'name' => 'Kabupaten Nias', 'ibukota' => 'Gunungsitoli', 'k_bsni' => 'GST'],
            ['id' => '28', 'provinsi_id' => '2', 'name' => 'Kabupaten Langkat', 'ibukota' => 'Stabat', 'k_bsni' => 'STB'],
            ['id' => '29', 'provinsi_id' => '2', 'name' => 'Kabupaten Karo', 'ibukota' => 'Kabanjahe', 'k_bsni' => 'KBJ'],
            ['id' => '30', 'provinsi_id' => '2', 'name' => 'Kabupaten Deli Serdang', 'ibukota' => 'Lubuk Pakam', 'k_bsni' => 'LBP'],
            ['id' => '31', 'provinsi_id' => '2', 'name' => 'Kabupaten Simalungun', 'ibukota' => 'Pematang Siantar', 'k_bsni' => 'PMS'],
            ['id' => '32', 'provinsi_id' => '2', 'name' => 'Kabupaten Asahan', 'ibukota' => 'Kisaran', 'k_bsni' => 'KIS'],
            ['id' => '33', 'provinsi_id' => '2', 'name' => 'Kabupaten Labuhanbatu', 'ibukota' => 'Rantau Prapat', 'k_bsni' => 'RAP'],
            ['id' => '34', 'provinsi_id' => '2', 'name' => 'Kabupaten Dairi', 'ibukota' => 'Sidikalang', 'k_bsni' => 'SDK'],
            ['id' => '35', 'provinsi_id' => '2', 'name' => 'Kabupaten Toba Samosir', 'ibukota' => 'Balige', 'k_bsni' => 'BLG'],
            ['id' => '36', 'provinsi_id' => '2', 'name' => 'Kabupaten Mandailing Natal', 'ibukota' => 'Panyabungan', 'k_bsni' => 'PYB'],
            ['id' => '37', 'provinsi_id' => '2', 'name' => 'Kabupaten Nias Selatan', 'ibukota' => 'Teluk Dalam', 'k_bsni' => 'TLD'],
            ['id' => '38', 'provinsi_id' => '2', 'name' => 'Kabupaten Pakpak Bharat', 'ibukota' => 'Salak', 'k_bsni' => 'SAL'],
            ['id' => '39', 'provinsi_id' => '2', 'name' => 'Kabupaten Humbang Hasundutan', 'ibukota' => 'Dolok Sanggul', 'k_bsni' => 'DLS'],
            ['id' => '40', 'provinsi_id' => '2', 'name' => 'Kabupaten Samosir', 'ibukota' => 'Pangururan', 'k_bsni' => 'PRR'],
            ['id' => '41', 'provinsi_id' => '2', 'name' => 'Kabupaten Serdang Bedagai', 'ibukota' => 'Sei Rampah', 'k_bsni' => 'SRH'],
            ['id' => '42', 'provinsi_id' => '2', 'name' => 'Kabupaten Batu Bara', 'ibukota' => 'Lima Puluh', 'k_bsni' => 'LMP'],
            ['id' => '43', 'provinsi_id' => '2', 'name' => 'Kabupaten Padang Lawas Utara', 'ibukota' => 'Gunung Tua', 'k_bsni' => 'GNT'],
            ['id' => '44', 'provinsi_id' => '2', 'name' => 'Kabupaten Padang Lawas', 'ibukota' => 'Sibuhuan', 'k_bsni' => 'SBH'],
            ['id' => '45', 'provinsi_id' => '2', 'name' => 'Kabupaten Labuhanbatu Selatan', 'ibukota' => 'Kota Pinang', 'k_bsni' => 'KPI'],
            ['id' => '46', 'provinsi_id' => '2', 'name' => 'Kabupaten Labuhanbatu Utara', 'ibukota' => 'Aek Kanopan', 'k_bsni' => 'AKK'],
            ['id' => '47', 'provinsi_id' => '2', 'name' => 'Kabupaten Nias Utara', 'ibukota' => 'Lotu', 'k_bsni' => 'LTU'],
            ['id' => '48', 'provinsi_id' => '2', 'name' => 'Kabupaten Nias Barat', 'ibukota' => 'Lahomi', 'k_bsni' => 'LHM'],
            ['id' => '49', 'provinsi_id' => '2', 'name' => 'Kota Medan', 'ibukota' => 'Medan', 'k_bsni' => 'MDN'],
            ['id' => '50', 'provinsi_id' => '2', 'name' => 'Kota Pematangsiantar', 'ibukota' => 'Pematangsiantar', 'k_bsni' => 'PMS'],
            ['id' => '51', 'provinsi_id' => '2', 'name' => 'Kota Sibolga', 'ibukota' => 'Sibolga', 'k_bsni' => 'SBG'],
            ['id' => '52', 'provinsi_id' => '2', 'name' => 'Kota Tanjung Balai', 'ibukota' => 'Tanjung Balai', 'k_bsni' => 'TJB'],
            ['id' => '53', 'provinsi_id' => '2', 'name' => 'Kota Binjai', 'ibukota' => 'Binjai', 'k_bsni' => 'BNJ'],
            ['id' => '54', 'provinsi_id' => '2', 'name' => 'Kota Tebing Tinggi', 'ibukota' => 'Tebing Tinggi', 'k_bsni' => 'TBT'],
            ['id' => '55', 'provinsi_id' => '2', 'name' => 'Kota Padang Sidempuan', 'ibukota' => 'Padang Sidempuan', 'k_bsni' => 'PSP'],
            ['id' => '56', 'provinsi_id' => '2', 'name' => 'Kota Gunungsitoli', 'ibukota' => 'Gunungsitoli', 'k_bsni' => 'GST'],
            ['id' => '57', 'provinsi_id' => '3', 'name' => 'Kabupaten Pesisir Selatan', 'ibukota' => 'Painan', 'k_bsni' => 'PNN'],
            ['id' => '58', 'provinsi_id' => '3', 'name' => 'Kabupaten Solok', 'ibukota' => 'Arosuka', 'k_bsni' => 'ARS'],
            ['id' => '59', 'provinsi_id' => '3', 'name' => 'Kabupaten Sijunjung (Sawah Lunto Sijunjung)', 'ibukota' => 'Muaro Sijunjung', 'k_bsni' => 'MRJ'],
            ['id' => '60', 'provinsi_id' => '3', 'name' => 'Kabupaten Tanah Datar', 'ibukota' => 'Batusangkar', 'k_bsni' => 'BSK'],
            ['id' => '61', 'provinsi_id' => '3', 'name' => 'Kabupaten Padang Pariaman', 'ibukota' => 'Nagari Parit Malintang', 'k_bsni' => 'NPM'],
            ['id' => '62', 'provinsi_id' => '3', 'name' => 'Kabupaten Agam', 'ibukota' => 'Lubuk Basung', 'k_bsni' => 'LBB'],
            ['id' => '63', 'provinsi_id' => '3', 'name' => 'Kabupaten Lima Puluh Kota', 'ibukota' => 'Sarilamak', 'k_bsni' => 'SRK'],
            ['id' => '64', 'provinsi_id' => '3', 'name' => 'Kabupaten Pasaman', 'ibukota' => 'Lubuk Sikaping', 'k_bsni' => 'LBS'],
            ['id' => '65', 'provinsi_id' => '3', 'name' => 'Kabupaten Kepulauan Mentawai', 'ibukota' => 'Tuapejat', 'k_bsni' => 'TPT'],
            ['id' => '66', 'provinsi_id' => '3', 'name' => 'Kabupaten Dharmasraya', 'ibukota' => 'Pulau Punjung', 'k_bsni' => 'PLJ'],
            ['id' => '67', 'provinsi_id' => '3', 'name' => 'Kabupaten Solok Selatan', 'ibukota' => 'Padang Aro', 'k_bsni' => 'PDA'],
            ['id' => '68', 'provinsi_id' => '3', 'name' => 'Kabupaten Pasaman Barat', 'ibukota' => 'Simpang Empat', 'k_bsni' => 'SPE'],
            ['id' => '69', 'provinsi_id' => '3', 'name' => 'Kota Padang', 'ibukota' => 'Padang', 'k_bsni' => 'PAD'],
            ['id' => '70', 'provinsi_id' => '3', 'name' => 'Kota Solok', 'ibukota' => 'Solok', 'k_bsni' => 'SLK'],
            ['id' => '71', 'provinsi_id' => '3', 'name' => 'Kota Sawahlunto', 'ibukota' => 'Sawahlunto', 'k_bsni' => 'SWL'],
            ['id' => '72', 'provinsi_id' => '3', 'name' => 'Kota Padang Panjang', 'ibukota' => 'Padang Panjang', 'k_bsni' => 'PDP'],
            ['id' => '73', 'provinsi_id' => '3', 'name' => 'Kota Bukittinggi', 'ibukota' => 'Bukittinggi', 'k_bsni' => 'BKT'],
            ['id' => '74', 'provinsi_id' => '3', 'name' => 'Kota Payakumbuh', 'ibukota' => 'Payakumbuh', 'k_bsni' => 'PYH'],
            ['id' => '75', 'provinsi_id' => '3', 'name' => 'Kota Pariaman', 'ibukota' => 'Pariaman', 'k_bsni' => 'PMN'],
            ['id' => '76', 'provinsi_id' => '4', 'name' => 'Kabupaten Kampar', 'ibukota' => 'Bangkinang', 'k_bsni' => 'BKN'],
            ['id' => '77', 'provinsi_id' => '4', 'name' => 'Kabupaten Indragiri Hulu', 'ibukota' => 'Rengat', 'k_bsni' => 'RGT'],
            ['id' => '78', 'provinsi_id' => '4', 'name' => 'Kabupaten Bengkalis', 'ibukota' => 'Bengkalis', 'k_bsni' => 'BLS'],
            ['id' => '79', 'provinsi_id' => '4', 'name' => 'Kabupaten Indragiri Hilir', 'ibukota' => 'Tembilahan', 'k_bsni' => 'TBH'],
            ['id' => '80', 'provinsi_id' => '4', 'name' => 'Kabupaten Pelalawan', 'ibukota' => 'Pangkalan Kerinci', 'k_bsni' => 'PKK'],
            ['id' => '81', 'provinsi_id' => '4', 'name' => 'Kabupaten Rokan Hulu', 'ibukota' => 'Pasir Pengarairan', 'k_bsni' => 'PRP'],
            ['id' => '82', 'provinsi_id' => '4', 'name' => 'Kabupaten Rokan Hilir', 'ibukota' => 'Ujung Tanjung', 'k_bsni' => 'UJT'],
            ['id' => '83', 'provinsi_id' => '4', 'name' => 'Kabupaten Siak', 'ibukota' => 'Siak Sriindrapura', 'k_bsni' => 'SAK'],
            ['id' => '84', 'provinsi_id' => '4', 'name' => 'Kabupaten Kuantan Singingi', 'ibukota' => 'Teluk Kuantan', 'k_bsni' => 'TLK'],
            ['id' => '85', 'provinsi_id' => '4', 'name' => 'Kabupaten Kepulauan Meranti', 'ibukota' => 'Tebing Tinggi', 'k_bsni' => 'TTG'],
            ['id' => '86', 'provinsi_id' => '4', 'name' => 'Kota Pekanbaru', 'ibukota' => 'Pekanbaru', 'k_bsni' => 'PBR'],
            ['id' => '87', 'provinsi_id' => '4', 'name' => 'Kota Dumai', 'ibukota' => 'Dumai', 'k_bsni' => 'DUM'],
            ['id' => '88', 'provinsi_id' => '5', 'name' => 'Kabupaten Kerinci', 'ibukota' => 'Sungai Penuh', 'k_bsni' => 'SPN'],
            ['id' => '89', 'provinsi_id' => '5', 'name' => 'Kabupaten Merangin', 'ibukota' => 'Bangko', 'k_bsni' => 'BKO'],
            ['id' => '90', 'provinsi_id' => '5', 'name' => 'Kabupaten Sarolangun', 'ibukota' => 'Sarolangun', 'k_bsni' => 'SRL'],
            ['id' => '91', 'provinsi_id' => '5', 'name' => 'Kabupaten Batanghari', 'ibukota' => 'Muara Bulian', 'k_bsni' => 'MBN'],
            ['id' => '92', 'provinsi_id' => '5', 'name' => 'Kabupaten Muaro Jambi', 'ibukota' => 'Sengeti', 'k_bsni' => 'SNT'],
            ['id' => '93', 'provinsi_id' => '5', 'name' => 'Kabupaten Tanjung Jabung Barat', 'ibukota' => 'Kuala Tungkal', 'k_bsni' => 'KLT'],
            ['id' => '94', 'provinsi_id' => '5', 'name' => 'Kabupaten Tanjung Jabung Timur', 'ibukota' => 'Muara Sabak', 'k_bsni' => 'MSK'],
            ['id' => '95', 'provinsi_id' => '5', 'name' => 'Kabupaten Bungo', 'ibukota' => 'Muara Bungo', 'k_bsni' => 'MRB'],
            ['id' => '96', 'provinsi_id' => '5', 'name' => 'Kabupaten Tebo', 'ibukota' => 'Muara Tebo', 'k_bsni' => 'MRT'],
            ['id' => '97', 'provinsi_id' => '5', 'name' => 'Kota Jambi', 'ibukota' => 'Jambi', 'k_bsni' => 'JMB'],
            ['id' => '98', 'provinsi_id' => '5', 'name' => 'Kota Sungai Penuh', 'ibukota' => 'Sungai Penuh', 'k_bsni' => 'SPN'],
            ['id' => '99', 'provinsi_id' => '6', 'name' => 'Kabupaten Ogan Komering Ulu', 'ibukota' => 'Baturaja', 'k_bsni' => 'BTA'],
            ['id' => '100', 'provinsi_id' => '6', 'name' => 'Kabupaten Ogan Komering Ilir', 'ibukota' => 'Kayu Agung', 'k_bsni' => 'KAG'],
            ['id' => '101', 'provinsi_id' => '6', 'name' => 'Kabupaten Muara Enim', 'ibukota' => 'Muara Enim', 'k_bsni' => 'MRE'],
            ['id' => '102', 'provinsi_id' => '6', 'name' => 'Kabupaten Lahat', 'ibukota' => 'Lahat', 'k_bsni' => 'LHT'],
            ['id' => '103', 'provinsi_id' => '6', 'name' => 'Kabupaten Musi Rawas', 'ibukota' => 'Muarabeliti', 'k_bsni' => 'MBL'],
            ['id' => '104', 'provinsi_id' => '6', 'name' => 'Kabupaten Musi Banyuasin', 'ibukota' => 'Sekayu', 'k_bsni' => 'SKY'],
            ['id' => '105', 'provinsi_id' => '6', 'name' => 'Kabupaten Banyuasin', 'ibukota' => 'Pangkalan Balai', 'k_bsni' => 'PKB'],
            ['id' => '106', 'provinsi_id' => '6', 'name' => 'Kabupaten Ogan Komering Ulu Timur (Oku Timur)', 'ibukota' => 'Martapura', 'k_bsni' => 'MPR'],
            ['id' => '107', 'provinsi_id' => '6', 'name' => 'Kabupaten Ogan Komering Ulu Selatan (Oku Selatan)', 'ibukota' => 'Muaradua', 'k_bsni' => 'MRD'],
            ['id' => '108', 'provinsi_id' => '6', 'name' => 'Kabupaten Ogan Ilir', 'ibukota' => 'Indralaya', 'k_bsni' => 'IDL'],
            ['id' => '109', 'provinsi_id' => '6', 'name' => 'Kabupaten Empat Lawang', 'ibukota' => 'Tebing Tinggi', 'k_bsni' => 'TBG'],
            ['id' => '110', 'provinsi_id' => '6', 'name' => 'Kota Palembang', 'ibukota' => 'Pelembang', 'k_bsni' => 'PLG'],
            ['id' => '111', 'provinsi_id' => '6', 'name' => 'Kota Pagar Alam', 'ibukota' => 'Pagar Alam', 'k_bsni' => 'PGA'],
            ['id' => '112', 'provinsi_id' => '6', 'name' => 'Kota Lubuk Linggau', 'ibukota' => 'Lubuk Linggau', 'k_bsni' => 'LLG'],
            ['id' => '113', 'provinsi_id' => '6', 'name' => 'Kota Prabumulih', 'ibukota' => 'Prabumulih', 'k_bsni' => 'PBM'],
            ['id' => '114', 'provinsi_id' => '7', 'name' => 'Kabupaten Bengkulu Selatan', 'ibukota' => 'Manna', 'k_bsni' => 'MNA'],
            ['id' => '115', 'provinsi_id' => '7', 'name' => 'Kabupaten Rejang Lebong', 'ibukota' => 'Curup', 'k_bsni' => 'CRP'],
            ['id' => '116', 'provinsi_id' => '7', 'name' => 'Kabupaten Bengkulu Utara', 'ibukota' => 'Arga Makmur', 'k_bsni' => 'AGM'],
            ['id' => '117', 'provinsi_id' => '7', 'name' => 'Kabupaten Kaur', 'ibukota' => 'Bintuhan', 'k_bsni' => 'BHN'],
            ['id' => '118', 'provinsi_id' => '7', 'name' => 'Kabupaten Seluma', 'ibukota' => 'Tais', 'k_bsni' => 'TAS'],
            ['id' => '119', 'provinsi_id' => '7', 'name' => 'Kabupaten Muko Muko', 'ibukota' => 'Mukomuko', 'k_bsni' => 'MKM'],
            ['id' => '120', 'provinsi_id' => '7', 'name' => 'Kabupaten Lebong', 'ibukota' => 'Tubei', 'k_bsni' => 'TUB'],
            ['id' => '121', 'provinsi_id' => '7', 'name' => 'Kabupaten Kepahiang', 'ibukota' => 'Kepahiang', 'k_bsni' => 'KPH'],
            ['id' => '122', 'provinsi_id' => '7', 'name' => 'Kabupaten Bengkulu Tengah', 'ibukota' => 'Karang Tinggi', 'k_bsni' => 'KRT'],
            ['id' => '123', 'provinsi_id' => '7', 'name' => 'Kota Bengkulu', 'ibukota' => 'Bengkulu', 'k_bsni' => 'BGL'],
            ['id' => '124', 'provinsi_id' => '8', 'name' => 'Kabupaten Lampung Selatan', 'ibukota' => 'Kalianda', 'k_bsni' => 'KLA'],
            ['id' => '125', 'provinsi_id' => '8', 'name' => 'Kabupaten Lampung Tengah', 'ibukota' => 'Gunung Sugih', 'k_bsni' => 'GNS'],
            ['id' => '126', 'provinsi_id' => '8', 'name' => 'Kabupaten Lampung Utara', 'ibukota' => 'Kotabumi', 'k_bsni' => 'KTB'],
            ['id' => '127', 'provinsi_id' => '8', 'name' => 'Kabupaten Lampung Barat', 'ibukota' => 'Liwa', 'k_bsni' => 'LIW'],
            ['id' => '128', 'provinsi_id' => '8', 'name' => 'Kabupaten Tulang Bawang', 'ibukota' => 'Menggala', 'k_bsni' => 'MGL'],
            ['id' => '129', 'provinsi_id' => '8', 'name' => 'Kabupaten Tanggamus', 'ibukota' => 'Kota Agung', 'k_bsni' => 'KOT'],
            ['id' => '130', 'provinsi_id' => '8', 'name' => 'Kabupaten Lampung Timur', 'ibukota' => 'Sukadana', 'k_bsni' => 'SDN'],
            ['id' => '131', 'provinsi_id' => '8', 'name' => 'Kabupaten Way Kanan', 'ibukota' => 'Blambangan Umpu', 'k_bsni' => 'BBU'],
            ['id' => '132', 'provinsi_id' => '8', 'name' => 'Kabupaten Pesawaran', 'ibukota' => 'Gedong Tataan', 'k_bsni' => 'GDT'],
            ['id' => '133', 'provinsi_id' => '8', 'name' => 'Kabupaten Pringsewu', 'ibukota' => 'Pringsewu', 'k_bsni' => 'PRW'],
            ['id' => '134', 'provinsi_id' => '8', 'name' => 'Kabupaten Mesuji', 'ibukota' => 'Mesuji', 'k_bsni' => 'MSJ'],
            ['id' => '135', 'provinsi_id' => '8', 'name' => 'Kabupaten Tulang Bawang Barat', 'ibukota' => 'Tulang Bawang Tengah', 'k_bsni' => 'TWG'],
            ['id' => '136', 'provinsi_id' => '8', 'name' => 'Kabupaten Pesisir Barat', 'ibukota' => 'Krui', 'k_bsni' => 'KRU'],
            ['id' => '137', 'provinsi_id' => '8', 'name' => 'Kota Bandar Lampung', 'ibukota' => 'Bandar Lampung', 'k_bsni' => 'BDL'],
            ['id' => '138', 'provinsi_id' => '8', 'name' => 'Kota Metro', 'ibukota' => 'Metro', 'k_bsni' => 'MET'],
            ['id' => '139', 'provinsi_id' => '9', 'name' => 'Kabupaten Bangka', 'ibukota' => 'Sungai Liat', 'k_bsni' => 'SGL'],
            ['id' => '140', 'provinsi_id' => '9', 'name' => 'Kabupaten Belitung', 'ibukota' => 'Tanjung Pandan', 'k_bsni' => 'TDN'],
            ['id' => '141', 'provinsi_id' => '9', 'name' => 'Kabupaten Bangka Selatan', 'ibukota' => 'Toboali', 'k_bsni' => 'TBL'],
            ['id' => '142', 'provinsi_id' => '9', 'name' => 'Kabupaten Bangka Tengah', 'ibukota' => 'Koba', 'k_bsni' => 'KBA'],
            ['id' => '143', 'provinsi_id' => '9', 'name' => 'Kabupaten Bangka Barat', 'ibukota' => 'Mentok', 'k_bsni' => 'MTK'],
            ['id' => '144', 'provinsi_id' => '9', 'name' => 'Kabupaten Belitung Timur', 'ibukota' => 'Manggar', 'k_bsni' => 'MGR'],
            ['id' => '145', 'provinsi_id' => '9', 'name' => 'Kota Pangkal Pinang', 'ibukota' => 'Pangkal Pinang', 'k_bsni' => 'PGP'],
            ['id' => '146', 'provinsi_id' => '10', 'name' => 'Kabupaten Bintan', 'ibukota' => 'Bandar Seri Bentan', 'k_bsni' => 'BSB'],
            ['id' => '147', 'provinsi_id' => '10', 'name' => 'Kabupaten Karimun', 'ibukota' => 'Tanjung Balai Karimun', 'k_bsni' => 'TBK'],
            ['id' => '148', 'provinsi_id' => '10', 'name' => 'Kabupaten Natuna', 'ibukota' => 'Ranai', 'k_bsni' => 'RAN'],
            ['id' => '149', 'provinsi_id' => '10', 'name' => 'Kabupaten Lingga', 'ibukota' => 'Daik Lingga', 'k_bsni' => 'DKL'],
            ['id' => '150', 'provinsi_id' => '10', 'name' => 'Kabupaten Kepulauan Anambas', 'ibukota' => 'Tarempa', 'k_bsni' => 'TRP'],
            ['id' => '151', 'provinsi_id' => '10', 'name' => 'Kota Batam', 'ibukota' => 'Batam', 'k_bsni' => 'BTM'],
            ['id' => '152', 'provinsi_id' => '10', 'name' => 'Kota Tanjung Pinang', 'ibukota' => 'Tanjung Pinang', 'k_bsni' => 'TPG'],
            ['id' => '153', 'provinsi_id' => '11', 'name' => 'Kabupaten Adm. Kepulauan Seribu', 'ibukota' => 'Kepulauan Seribu Utara', 'k_bsni' => 'KSU'],
            ['id' => '154', 'provinsi_id' => '11', 'name' => 'Kota Adm. Jakarta Pusat', 'ibukota' => 'Tanah Abang', 'k_bsni' => 'TNA'],
            ['id' => '155', 'provinsi_id' => '11', 'name' => 'Kota Adm. Jakarta Utara', 'ibukota' => 'Tanjung Priok', 'k_bsni' => 'TJP'],
            ['id' => '156', 'provinsi_id' => '11', 'name' => 'Kota Adm. Jakarta Barat', 'ibukota' => 'Grogol Petamburan', 'k_bsni' => 'GGP'],
            ['id' => '157', 'provinsi_id' => '11', 'name' => 'Kota Adm. Jakarta Selatan', 'ibukota' => 'Kebayoran Baru', 'k_bsni' => 'KYB'],
            ['id' => '158', 'provinsi_id' => '11', 'name' => 'Kota Adm. Jakarta Timur', 'ibukota' => 'Cakung', 'k_bsni' => 'CKG'],
            ['id' => '159', 'provinsi_id' => '12', 'name' => 'Kabupaten Bogor', 'ibukota' => 'Cibinong', 'k_bsni' => 'CBI'],
            ['id' => '160', 'provinsi_id' => '12', 'name' => 'Kabupaten Sukabumi', 'ibukota' => 'Sukabumi', 'k_bsni' => 'SBM'],
            ['id' => '161', 'provinsi_id' => '12', 'name' => 'Kabupaten Cianjur', 'ibukota' => 'Cianjur', 'k_bsni' => 'CJR'],
            ['id' => '162', 'provinsi_id' => '12', 'name' => 'Kabupaten Bandung', 'ibukota' => 'Soreang', 'k_bsni' => 'SOR'],
            ['id' => '163', 'provinsi_id' => '12', 'name' => 'Kabupaten Garut', 'ibukota' => 'Garut', 'k_bsni' => 'GRT'],
            ['id' => '164', 'provinsi_id' => '12', 'name' => 'Kabupaten Tasikmalaya', 'ibukota' => 'Singaparna', 'k_bsni' => 'SPA'],
            ['id' => '165', 'provinsi_id' => '12', 'name' => 'Kabupaten Ciamis', 'ibukota' => 'Ciamis', 'k_bsni' => 'CMS'],
            ['id' => '166', 'provinsi_id' => '12', 'name' => 'Kabupaten Kuningan', 'ibukota' => 'Kuningan', 'k_bsni' => 'KNG'],
            ['id' => '167', 'provinsi_id' => '12', 'name' => 'Kabupaten Cirebon', 'ibukota' => 'Sumber', 'k_bsni' => 'SBR'],
            ['id' => '168', 'provinsi_id' => '12', 'name' => 'Kabupaten Majalengka', 'ibukota' => 'Majalengka', 'k_bsni' => 'MJL'],
            ['id' => '169', 'provinsi_id' => '12', 'name' => 'Kabupaten Sumedang', 'ibukota' => 'Sumedang', 'k_bsni' => 'SMD'],
            ['id' => '170', 'provinsi_id' => '12', 'name' => 'Kabupaten Indramayu', 'ibukota' => 'Indramayu', 'k_bsni' => 'IDM'],
            ['id' => '171', 'provinsi_id' => '12', 'name' => 'Kabupaten Subang', 'ibukota' => 'Subang', 'k_bsni' => 'SNG'],
            ['id' => '172', 'provinsi_id' => '12', 'name' => 'Kabupaten Purwakarta', 'ibukota' => 'Purwakarta', 'k_bsni' => 'PWK'],
            ['id' => '173', 'provinsi_id' => '12', 'name' => 'Kabupaten Karawang', 'ibukota' => 'Karawang', 'k_bsni' => 'KWG'],
            ['id' => '174', 'provinsi_id' => '12', 'name' => 'Kabupaten Bekasi', 'ibukota' => 'Cikarang', 'k_bsni' => 'CKR'],
            ['id' => '175', 'provinsi_id' => '12', 'name' => 'Kabupaten Bandung Barat', 'ibukota' => 'Ngamprah', 'k_bsni' => 'NPH'],
            ['id' => '176', 'provinsi_id' => '12', 'name' => 'Kabupaten Pangandaran', 'ibukota' => 'Parigi', 'k_bsni' => 'PAG'],
            ['id' => '177', 'provinsi_id' => '12', 'name' => 'Kota Bogor', 'ibukota' => 'Bogor', 'k_bsni' => 'BGR'],
            ['id' => '178', 'provinsi_id' => '12', 'name' => 'Kota Sukabumi', 'ibukota' => 'Sukabumi', 'k_bsni' => 'SKB'],
            ['id' => '179', 'provinsi_id' => '12', 'name' => 'Kota Bandung', 'ibukota' => 'Bandung', 'k_bsni' => 'BDG'],
            ['id' => '180', 'provinsi_id' => '12', 'name' => 'Kota Cirebon', 'ibukota' => 'Cirebon', 'k_bsni' => 'CBN'],
            ['id' => '181', 'provinsi_id' => '12', 'name' => 'Kota Bekasi', 'ibukota' => 'Bekasi', 'k_bsni' => 'BKS'],
            ['id' => '182', 'provinsi_id' => '12', 'name' => 'Kota Depok', 'ibukota' => 'Depok', 'k_bsni' => 'DPK'],
            ['id' => '183', 'provinsi_id' => '12', 'name' => 'Kota Cimahi', 'ibukota' => 'Cimahi', 'k_bsni' => 'CMH'],
            ['id' => '184', 'provinsi_id' => '12', 'name' => 'Kota Tasikmalaya', 'ibukota' => 'Tasikmalaya', 'k_bsni' => 'TSM'],
            ['id' => '185', 'provinsi_id' => '12', 'name' => 'Kota Banjar', 'ibukota' => 'Banjar', 'k_bsni' => 'BJR'],
            ['id' => '186', 'provinsi_id' => '13', 'name' => 'Kabupaten Cilacap', 'ibukota' => 'Cilacap', 'k_bsni' => 'CLP'],
            ['id' => '187', 'provinsi_id' => '13', 'name' => 'Kabupaten Banyumas', 'ibukota' => 'Purwokerto', 'k_bsni' => 'PWT'],
            ['id' => '188', 'provinsi_id' => '13', 'name' => 'Kabupaten Purbalingga', 'ibukota' => 'Purbalingga', 'k_bsni' => 'PBG'],
            ['id' => '189', 'provinsi_id' => '13', 'name' => 'Kabupaten Banjarnegara', 'ibukota' => 'Banjarnegara', 'k_bsni' => 'BNR'],
            ['id' => '190', 'provinsi_id' => '13', 'name' => 'Kabupaten Kebumen', 'ibukota' => 'Kebumen', 'k_bsni' => 'KBM'],
            ['id' => '191', 'provinsi_id' => '13', 'name' => 'Kabupaten Purworejo', 'ibukota' => 'Purworejo', 'k_bsni' => 'PWR'],
            ['id' => '192', 'provinsi_id' => '13', 'name' => 'Kabupaten Wonosobo', 'ibukota' => 'Wonosobo', 'k_bsni' => 'WSB'],
            ['id' => '193', 'provinsi_id' => '13', 'name' => 'Kabupaten Magelang', 'ibukota' => 'Mungkid', 'k_bsni' => 'MKD'],
            ['id' => '194', 'provinsi_id' => '13', 'name' => 'Kabupaten Boyolali', 'ibukota' => 'Boyolali', 'k_bsni' => 'BYL'],
            ['id' => '195', 'provinsi_id' => '13', 'name' => 'Kabupaten Klaten', 'ibukota' => 'Klaten', 'k_bsni' => 'KLN'],
            ['id' => '196', 'provinsi_id' => '13', 'name' => 'Kabupaten Sukoharjo', 'ibukota' => 'Sukoharjo', 'k_bsni' => 'SKH'],
            ['id' => '197', 'provinsi_id' => '13', 'name' => 'Kabupaten Wonogiri', 'ibukota' => 'Wonogiri', 'k_bsni' => 'WNG'],
            ['id' => '198', 'provinsi_id' => '13', 'name' => 'Kabupaten Karanganyar', 'ibukota' => 'Karanganyar', 'k_bsni' => 'KRG'],
            ['id' => '199', 'provinsi_id' => '13', 'name' => 'Kabupaten Sragen', 'ibukota' => 'Sragen', 'k_bsni' => 'SGN'],
            ['id' => '200', 'provinsi_id' => '13', 'name' => 'Kabupaten Grobogan', 'ibukota' => 'Purwodadi', 'k_bsni' => 'PWD'],
            ['id' => '201', 'provinsi_id' => '13', 'name' => 'Kabupaten Blora', 'ibukota' => 'Blora', 'k_bsni' => 'BLA'],
            ['id' => '202', 'provinsi_id' => '13', 'name' => 'Kabupaten Rembang', 'ibukota' => 'Rembang', 'k_bsni' => 'RBG'],
            ['id' => '203', 'provinsi_id' => '13', 'name' => 'Kabupaten Pati', 'ibukota' => 'Pati', 'k_bsni' => 'PTI'],
            ['id' => '204', 'provinsi_id' => '13', 'name' => 'Kabupaten Kudus', 'ibukota' => 'Kudus', 'k_bsni' => 'KDS'],
            ['id' => '205', 'provinsi_id' => '13', 'name' => 'Kabupaten Jepara', 'ibukota' => 'Jepara', 'k_bsni' => 'JPA'],
            ['id' => '206', 'provinsi_id' => '13', 'name' => 'Kabupaten Demak', 'ibukota' => 'Demak', 'k_bsni' => 'DMK'],
            ['id' => '207', 'provinsi_id' => '13', 'name' => 'Kabupaten Semarang', 'ibukota' => 'Ungaran', 'k_bsni' => 'UNR'],
            ['id' => '208', 'provinsi_id' => '13', 'name' => 'Kabupaten Temanggung', 'ibukota' => 'Temanggung', 'k_bsni' => 'TMG'],
            ['id' => '209', 'provinsi_id' => '13', 'name' => 'Kabupaten Kendal', 'ibukota' => 'Kendal', 'k_bsni' => 'KDL'],
            ['id' => '210', 'provinsi_id' => '13', 'name' => 'Kabupaten Batang', 'ibukota' => 'Batang', 'k_bsni' => 'BTG'],
            ['id' => '211', 'provinsi_id' => '13', 'name' => 'Kabupaten Pekalongan', 'ibukota' => 'Kajen', 'k_bsni' => 'KJN'],
            ['id' => '212', 'provinsi_id' => '13', 'name' => 'Kabupaten Pemalang', 'ibukota' => 'Pemalang', 'k_bsni' => 'PML'],
            ['id' => '213', 'provinsi_id' => '13', 'name' => 'Kabupaten Tegal', 'ibukota' => 'Slawi', 'k_bsni' => 'SLW'],
            ['id' => '214', 'provinsi_id' => '13', 'name' => 'Kabupaten Brebes', 'ibukota' => 'Brebes', 'k_bsni' => 'BBS'],
            ['id' => '215', 'provinsi_id' => '13', 'name' => 'Kota Magelang', 'ibukota' => 'Magelang', 'k_bsni' => 'MGG'],
            ['id' => '216', 'provinsi_id' => '13', 'name' => 'Kota Surakarta (Solo)', 'ibukota' => 'Surakarta', 'k_bsni' => 'SKT'],
            ['id' => '217', 'provinsi_id' => '13', 'name' => 'Kota Salatiga', 'ibukota' => 'Salatiga', 'k_bsni' => 'SLT'],
            ['id' => '218', 'provinsi_id' => '13', 'name' => 'Kota Semarang', 'ibukota' => 'Semarang', 'k_bsni' => 'SMG'],
            ['id' => '219', 'provinsi_id' => '13', 'name' => 'Kota Pekalongan', 'ibukota' => 'Pekalongan', 'k_bsni' => 'PKL'],
            ['id' => '220', 'provinsi_id' => '13', 'name' => 'Kota Tegal', 'ibukota' => 'Tegal', 'k_bsni' => 'TGL'],
            ['id' => '221', 'provinsi_id' => '14', 'name' => 'Kabupaten Kulon Progo', 'ibukota' => 'Wates', 'k_bsni' => 'WAT'],
            ['id' => '222', 'provinsi_id' => '14', 'name' => 'Kabupaten Bantul', 'ibukota' => 'Bantul', 'k_bsni' => 'BTL'],
            ['id' => '223', 'provinsi_id' => '14', 'name' => 'Kabupaten Gunung Kidul', 'ibukota' => 'Wonosari', 'k_bsni' => 'WNO'],
            ['id' => '224', 'provinsi_id' => '14', 'name' => 'Kabupaten Sleman', 'ibukota' => 'Sleman', 'k_bsni' => 'SMN'],
            ['id' => '225', 'provinsi_id' => '14', 'name' => 'Kota Yogyakarta', 'ibukota' => 'Yogyakarta', 'k_bsni' => 'YYK'],
            ['id' => '226', 'provinsi_id' => '15', 'name' => 'Kabupaten Pacitan', 'ibukota' => 'Pacitan', 'k_bsni' => 'PCT'],
            ['id' => '227', 'provinsi_id' => '15', 'name' => 'Kabupaten Ponorogo', 'ibukota' => 'Ponorogo', 'k_bsni' => 'PNG'],
            ['id' => '228', 'provinsi_id' => '15', 'name' => 'Kabupaten Trenggalek', 'ibukota' => 'Trenggalek', 'k_bsni' => 'TRK'],
            ['id' => '229', 'provinsi_id' => '15', 'name' => 'Kabupaten Tulungagung', 'ibukota' => 'Tulungagung', 'k_bsni' => 'TLG'],
            ['id' => '230', 'provinsi_id' => '15', 'name' => 'Kabupaten Blitar', 'ibukota' => 'Kanigoro', 'k_bsni' => 'KNR'],
            ['id' => '231', 'provinsi_id' => '15', 'name' => 'Kabupaten Kediri', 'ibukota' => 'Kediri', 'k_bsni' => 'KDR'],
            ['id' => '232', 'provinsi_id' => '15', 'name' => 'Kabupaten Malang', 'ibukota' => 'Kepanjen', 'k_bsni' => 'KPN'],
            ['id' => '233', 'provinsi_id' => '15', 'name' => 'Kabupaten Lumajang', 'ibukota' => 'Lumajang', 'k_bsni' => 'LMJ'],
            ['id' => '234', 'provinsi_id' => '15', 'name' => 'Kabupaten Jember', 'ibukota' => 'Jember', 'k_bsni' => 'JMR'],
            ['id' => '235', 'provinsi_id' => '15', 'name' => 'Kabupaten Banyuwangi', 'ibukota' => 'Banyuwangi', 'k_bsni' => 'BYW'],
            ['id' => '236', 'provinsi_id' => '15', 'name' => 'Kabupaten Bondowoso', 'ibukota' => 'Bondowoso', 'k_bsni' => 'BDW'],
            ['id' => '237', 'provinsi_id' => '15', 'name' => 'Kabupaten Situbondo', 'ibukota' => 'Situbondo', 'k_bsni' => 'SIT'],
            ['id' => '238', 'provinsi_id' => '15', 'name' => 'Kabupaten Probolinggo', 'ibukota' => 'Kraksaan', 'k_bsni' => 'KRS'],
            ['id' => '239', 'provinsi_id' => '15', 'name' => 'Kabupaten Pasuruan', 'ibukota' => 'Pasuruan', 'k_bsni' => 'PSR'],
            ['id' => '240', 'provinsi_id' => '15', 'name' => 'Kabupaten Sidoarjo', 'ibukota' => 'Sidoarjo', 'k_bsni' => 'SDA'],
            ['id' => '241', 'provinsi_id' => '15', 'name' => 'Kabupaten Mojokerto', 'ibukota' => 'Mojokerto', 'k_bsni' => 'MJK'],
            ['id' => '242', 'provinsi_id' => '15', 'name' => 'Kabupaten Jombang', 'ibukota' => 'Jombang', 'k_bsni' => 'JBG'],
            ['id' => '243', 'provinsi_id' => '15', 'name' => 'Kabupaten Nganjuk', 'ibukota' => 'Nganjuk', 'k_bsni' => 'NJK'],
            ['id' => '244', 'provinsi_id' => '15', 'name' => 'Kabupaten Madiun', 'ibukota' => 'Mejayan', 'k_bsni' => 'MJY'],
            ['id' => '245', 'provinsi_id' => '15', 'name' => 'Kabupaten Magetan', 'ibukota' => 'Magetan', 'k_bsni' => 'MGT'],
            ['id' => '246', 'provinsi_id' => '15', 'name' => 'Kabupaten Ngawi', 'ibukota' => 'Ngawi', 'k_bsni' => 'NGW'],
            ['id' => '247', 'provinsi_id' => '15', 'name' => 'Kabupaten Bojonegoro', 'ibukota' => 'Bojonegoro', 'k_bsni' => 'BJN'],
            ['id' => '248', 'provinsi_id' => '15', 'name' => 'Kabupaten Tuban', 'ibukota' => 'Tuban', 'k_bsni' => 'TBN'],
            ['id' => '249', 'provinsi_id' => '15', 'name' => 'Kabupaten Lamongan', 'ibukota' => 'Lamongan', 'k_bsni' => 'LMG'],
            ['id' => '250', 'provinsi_id' => '15', 'name' => 'Kabupaten Gresik', 'ibukota' => 'Gresik', 'k_bsni' => 'GSK'],
            ['id' => '251', 'provinsi_id' => '15', 'name' => 'Kabupaten Bangkalan', 'ibukota' => 'Bangkalan', 'k_bsni' => 'BKL'],
            ['id' => '252', 'provinsi_id' => '15', 'name' => 'Kabupaten Sampang', 'ibukota' => 'Sampang', 'k_bsni' => 'SPG'],
            ['id' => '253', 'provinsi_id' => '15', 'name' => 'Kabupaten Pamekasan', 'ibukota' => 'Pamekasan', 'k_bsni' => 'PMK'],
            ['id' => '254', 'provinsi_id' => '15', 'name' => 'Kabupaten Sumenep', 'ibukota' => 'Sumenep', 'k_bsni' => 'SMP'],
            ['id' => '255', 'provinsi_id' => '15', 'name' => 'Kota Kediri', 'ibukota' => 'Kediri', 'k_bsni' => 'KDR'],
            ['id' => '256', 'provinsi_id' => '15', 'name' => 'Kota Blitar', 'ibukota' => 'Blitar', 'k_bsni' => 'BLT'],
            ['id' => '257', 'provinsi_id' => '15', 'name' => 'Kota Malang', 'ibukota' => 'Malang', 'k_bsni' => 'MLG'],
            ['id' => '258', 'provinsi_id' => '15', 'name' => 'Kota Probolinggo', 'ibukota' => 'Probolinggo', 'k_bsni' => 'PBL'],
            ['id' => '259', 'provinsi_id' => '15', 'name' => 'Kota Pasuruan', 'ibukota' => 'Pasuruan', 'k_bsni' => 'PSN'],
            ['id' => '260', 'provinsi_id' => '15', 'name' => 'Kota Mojokerto', 'ibukota' => 'Mojokerto', 'k_bsni' => 'MJK'],
            ['id' => '261', 'provinsi_id' => '15', 'name' => 'Kota Madiun', 'ibukota' => 'Madiun', 'k_bsni' => 'MAD'],
            ['id' => '262', 'provinsi_id' => '15', 'name' => 'Kota Surabaya', 'ibukota' => 'Surabaya', 'k_bsni' => 'SBY'],
            ['id' => '263', 'provinsi_id' => '15', 'name' => 'Kota Batu', 'ibukota' => 'Batu', 'k_bsni' => 'BTU'],
            ['id' => '264', 'provinsi_id' => '16', 'name' => 'Kabupaten Pandeglang', 'ibukota' => 'Pandeglang', 'k_bsni' => 'PDG'],
            ['id' => '265', 'provinsi_id' => '16', 'name' => 'Kabupaten Lebak', 'ibukota' => 'Rangkas Bitung', 'k_bsni' => 'RKB'],
            ['id' => '266', 'provinsi_id' => '16', 'name' => 'Kabupaten Tangerang', 'ibukota' => 'Tigaraksa', 'k_bsni' => 'TGR'],
            ['id' => '267', 'provinsi_id' => '16', 'name' => 'Kabupaten Serang', 'ibukota' => 'Serang', 'k_bsni' => 'SRG'],
            ['id' => '268', 'provinsi_id' => '16', 'name' => 'Kota Tangerang', 'ibukota' => 'Tangerang', 'k_bsni' => 'TNG'],
            ['id' => '269', 'provinsi_id' => '16', 'name' => 'Kota Cilegon', 'ibukota' => 'Cilegon', 'k_bsni' => 'CLG'],
            ['id' => '270', 'provinsi_id' => '16', 'name' => 'Kota Serang', 'ibukota' => 'Serang', 'k_bsni' => 'SRG'],
            ['id' => '271', 'provinsi_id' => '16', 'name' => 'Kota Tangerang Selatan', 'ibukota' => 'Ciputat', 'k_bsni' => 'CPT'],
            ['id' => '272', 'provinsi_id' => '17', 'name' => 'Kabupaten Jembrana', 'ibukota' => 'Negara', 'k_bsni' => 'NGA'],
            ['id' => '273', 'provinsi_id' => '17', 'name' => 'Kabupaten Tabanan', 'ibukota' => 'Tabanan', 'k_bsni' => 'TAB'],
            ['id' => '274', 'provinsi_id' => '17', 'name' => 'Kabupaten Badung', 'ibukota' => 'Mengwi', 'k_bsni' => 'MGW'],
            ['id' => '275', 'provinsi_id' => '17', 'name' => 'Kabupaten Gianyar', 'ibukota' => 'Gianyar', 'k_bsni' => 'GIN'],
            ['id' => '276', 'provinsi_id' => '17', 'name' => 'Kabupaten Klungkung', 'ibukota' => 'Semarapura', 'k_bsni' => 'SRP'],
            ['id' => '277', 'provinsi_id' => '17', 'name' => 'Kabupaten Bangli', 'ibukota' => 'Bangli', 'k_bsni' => 'BLI'],
            ['id' => '278', 'provinsi_id' => '17', 'name' => 'Kabupaten Karangasem', 'ibukota' => 'Karangasem', 'k_bsni' => 'KRA'],
            ['id' => '279', 'provinsi_id' => '17', 'name' => 'Kabupaten Buleleng', 'ibukota' => 'Singaraja', 'k_bsni' => 'SGR'],
            ['id' => '280', 'provinsi_id' => '17', 'name' => 'Kota Denpasar', 'ibukota' => 'Denpasar', 'k_bsni' => 'DPR'],
            ['id' => '281', 'provinsi_id' => '18', 'name' => 'Kabupaten Lombok Barat', 'ibukota' => 'Gerung', 'k_bsni' => 'GRG'],
            ['id' => '282', 'provinsi_id' => '18', 'name' => 'Kabupaten Lombok Tengah', 'ibukota' => 'Praya', 'k_bsni' => 'PYA'],
            ['id' => '283', 'provinsi_id' => '18', 'name' => 'Kabupaten Lombok Timur', 'ibukota' => 'Selong', 'k_bsni' => 'SEL'],
            ['id' => '284', 'provinsi_id' => '18', 'name' => 'Kabupaten Sumbawa', 'ibukota' => 'Sumbawa Besar', 'k_bsni' => 'SBW'],
            ['id' => '285', 'provinsi_id' => '18', 'name' => 'Kabupaten Dompu', 'ibukota' => 'Dompu', 'k_bsni' => 'DPU'],
            ['id' => '286', 'provinsi_id' => '18', 'name' => 'Kabupaten Bima', 'ibukota' => 'Woha', 'k_bsni' => 'WHO'],
            ['id' => '287', 'provinsi_id' => '18', 'name' => 'Kabupaten Sumbawa Barat', 'ibukota' => 'Taliwang', 'k_bsni' => 'TLW'],
            ['id' => '288', 'provinsi_id' => '18', 'name' => 'Kabupaten Lombok Utara', 'ibukota' => 'Tanjung', 'k_bsni' => 'TJN'],
            ['id' => '289', 'provinsi_id' => '18', 'name' => 'Kota Mataram', 'ibukota' => 'Mataram', 'k_bsni' => 'MTR'],
            ['id' => '290', 'provinsi_id' => '18', 'name' => 'Kota Bima', 'ibukota' => 'Bima', 'k_bsni' => 'BIM'],
            ['id' => '291', 'provinsi_id' => '19', 'name' => 'Kabupaten Kupang', 'ibukota' => 'Kupang', 'k_bsni' => 'KPG'],
            ['id' => '292', 'provinsi_id' => '19', 'name' => 'Kabupaten Timor Tengah Selatan', 'ibukota' => 'Soe', 'k_bsni' => 'SOE'],
            ['id' => '293', 'provinsi_id' => '19', 'name' => 'Kabupaten Timor Tengah Utara', 'ibukota' => 'Kefamenanu', 'k_bsni' => 'KFM'],
            ['id' => '294', 'provinsi_id' => '19', 'name' => 'Kabupaten Belu', 'ibukota' => 'Atambua', 'k_bsni' => 'ATB'],
            ['id' => '295', 'provinsi_id' => '19', 'name' => 'Kabupaten Alor', 'ibukota' => 'Kalabahi', 'k_bsni' => 'KLB'],
            ['id' => '296', 'provinsi_id' => '19', 'name' => 'Kabupaten Flores Timur', 'ibukota' => 'Larantuka', 'k_bsni' => 'LRT'],
            ['id' => '297', 'provinsi_id' => '19', 'name' => 'Kabupaten Sikka', 'ibukota' => 'Maumere', 'k_bsni' => 'MME'],
            ['id' => '298', 'provinsi_id' => '19', 'name' => 'Kabupaten Ende', 'ibukota' => 'Ende', 'k_bsni' => 'END'],
            ['id' => '299', 'provinsi_id' => '19', 'name' => 'Kabupaten Ngada', 'ibukota' => 'Bajawa', 'k_bsni' => 'BJW'],
            ['id' => '300', 'provinsi_id' => '19', 'name' => 'Kabupaten Manggarai', 'ibukota' => 'Ruteng', 'k_bsni' => 'RTG'],
            ['id' => '301', 'provinsi_id' => '19', 'name' => 'Kabupaten Sumba Timur', 'ibukota' => 'Waingapu', 'k_bsni' => 'WGP'],
            ['id' => '302', 'provinsi_id' => '19', 'name' => 'Kabupaten Sumba Barat', 'ibukota' => 'Waikabubak', 'k_bsni' => 'WKB'],
            ['id' => '303', 'provinsi_id' => '19', 'name' => 'Kabupaten Lembata', 'ibukota' => 'Lewoleba', 'k_bsni' => 'LWL'],
            ['id' => '304', 'provinsi_id' => '19', 'name' => 'Kabupaten Rote Ndao', 'ibukota' => 'Baa', 'k_bsni' => 'BAA'],
            ['id' => '305', 'provinsi_id' => '19', 'name' => 'Kabupaten Manggarai Barat', 'ibukota' => 'Labuan Bajo', 'k_bsni' => 'LBJ'],
            ['id' => '306', 'provinsi_id' => '19', 'name' => 'Kabupaten Nagekeo', 'ibukota' => 'Mbay', 'k_bsni' => 'MBY'],
            ['id' => '307', 'provinsi_id' => '19', 'name' => 'Kabupaten Sumba Tengah', 'ibukota' => 'Waibakul', 'k_bsni' => 'WBL'],
            ['id' => '308', 'provinsi_id' => '19', 'name' => 'Kabupaten Sumba Barat Daya', 'ibukota' => 'Tambolaka', 'k_bsni' => 'TAM'],
            ['id' => '309', 'provinsi_id' => '19', 'name' => 'Kabupaten Manggarai Timur', 'ibukota' => 'Borong', 'k_bsni' => 'BRG'],
            ['id' => '310', 'provinsi_id' => '19', 'name' => 'Kabupaten Sabu Raijua', 'ibukota' => 'Sabu Barat', 'k_bsni' => 'SBB'],
            ['id' => '311', 'provinsi_id' => '19', 'name' => 'Kota Kupang', 'ibukota' => 'Kupang', 'k_bsni' => 'KPG'],
            ['id' => '312', 'provinsi_id' => '20', 'name' => 'Kabupaten Sambas', 'ibukota' => 'Sambas', 'k_bsni' => 'SBS'],
            ['id' => '313', 'provinsi_id' => '20', 'name' => 'Kabupaten Pontianak', 'ibukota' => 'Mempawah', 'k_bsni' => 'MPW'],
            ['id' => '314', 'provinsi_id' => '20', 'name' => 'Kabupaten Sanggau', 'ibukota' => 'Sanggau', 'k_bsni' => 'SAG'],
            ['id' => '315', 'provinsi_id' => '20', 'name' => 'Kabupaten Ketapang', 'ibukota' => 'Ketapang', 'k_bsni' => 'KTP'],
            ['id' => '316', 'provinsi_id' => '20', 'name' => 'Kabupaten Sintang', 'ibukota' => 'Sintang', 'k_bsni' => 'STG'],
            ['id' => '317', 'provinsi_id' => '20', 'name' => 'Kabupaten Kapuas Hulu', 'ibukota' => 'Putussibau', 'k_bsni' => 'PTS'],
            ['id' => '318', 'provinsi_id' => '20', 'name' => 'Kabupaten Bengkayang', 'ibukota' => 'Bengkayang', 'k_bsni' => 'BEK'],
            ['id' => '319', 'provinsi_id' => '20', 'name' => 'Kabupaten Landak', 'ibukota' => 'Ngabang', 'k_bsni' => 'NBA'],
            ['id' => '320', 'provinsi_id' => '20', 'name' => 'Kabupaten Sekadau', 'ibukota' => 'Sekadau', 'k_bsni' => 'SED'],
            ['id' => '321', 'provinsi_id' => '20', 'name' => 'Kabupaten Melawi', 'ibukota' => 'Nanga Pinoh', 'k_bsni' => 'NGP'],
            ['id' => '322', 'provinsi_id' => '20', 'name' => 'Kabupaten Kayong Utara', 'ibukota' => 'Sukadane', 'k_bsni' => 'SKD'],
            ['id' => '323', 'provinsi_id' => '20', 'name' => 'Kabupaten Kubu Raya', 'ibukota' => 'Sungai Raya', 'k_bsni' => 'SRY'],
            ['id' => '324', 'provinsi_id' => '20', 'name' => 'Kota Pontianak', 'ibukota' => 'Pontianak', 'k_bsni' => 'PTK'],
            ['id' => '325', 'provinsi_id' => '20', 'name' => 'Kota Singkawang', 'ibukota' => 'Singkawang', 'k_bsni' => 'SKW'],
            ['id' => '326', 'provinsi_id' => '21', 'name' => 'Kabupaten Kotawaringin Barat', 'ibukota' => 'Pangkalan Bun', 'k_bsni' => 'PBU'],
            ['id' => '327', 'provinsi_id' => '21', 'name' => 'Kabupaten Kotawaringin Timur', 'ibukota' => 'Sampit', 'k_bsni' => 'SPT'],
            ['id' => '328', 'provinsi_id' => '21', 'name' => 'Kabupaten Kapuas', 'ibukota' => 'Kuala Kapuas', 'k_bsni' => 'KLK'],
            ['id' => '329', 'provinsi_id' => '21', 'name' => 'Kabupaten Barito Selatan', 'ibukota' => 'Buntok', 'k_bsni' => 'BNT'],
            ['id' => '330', 'provinsi_id' => '21', 'name' => 'Kabupaten Barito Utara', 'ibukota' => 'Muara Teweh', 'k_bsni' => 'MTW'],
            ['id' => '331', 'provinsi_id' => '21', 'name' => 'Kabupaten Katingan', 'ibukota' => 'Kasongan', 'k_bsni' => 'KSN'],
            ['id' => '332', 'provinsi_id' => '21', 'name' => 'Kabupaten Seruyan', 'ibukota' => 'Kuala Pembuang', 'k_bsni' => 'KLP'],
            ['id' => '333', 'provinsi_id' => '21', 'name' => 'Kabupaten Sukamara', 'ibukota' => 'Sukamara', 'k_bsni' => 'SKR'],
            ['id' => '334', 'provinsi_id' => '21', 'name' => 'Kabupaten Lamandau', 'ibukota' => 'Nanga Bulik', 'k_bsni' => 'NGB'],
            ['id' => '335', 'provinsi_id' => '21', 'name' => 'Kabupaten Gunung Mas', 'ibukota' => 'Kuala Kurun', 'k_bsni' => 'KKN'],
            ['id' => '336', 'provinsi_id' => '21', 'name' => 'Kabupaten Pulang Pisau', 'ibukota' => 'Pulang Pisau', 'k_bsni' => 'PPS'],
            ['id' => '337', 'provinsi_id' => '21', 'name' => 'Kabupaten Murung Raya', 'ibukota' => 'Puruk Cahu', 'k_bsni' => 'PRC'],
            ['id' => '338', 'provinsi_id' => '21', 'name' => 'Kabupaten Barito Timur', 'ibukota' => 'Tamiang Layang', 'k_bsni' => 'TML'],
            ['id' => '339', 'provinsi_id' => '21', 'name' => 'Kota Palangka Raya', 'ibukota' => 'Palangkaraya', 'k_bsni' => 'PLK'],
            ['id' => '340', 'provinsi_id' => '22', 'name' => 'Kabupaten Tanah Laut', 'ibukota' => 'Pelaihari', 'k_bsni' => 'PLI'],
            ['id' => '341', 'provinsi_id' => '22', 'name' => 'Kabupaten Kotabaru', 'ibukota' => 'Kotabaru', 'k_bsni' => 'KBR'],
            ['id' => '342', 'provinsi_id' => '22', 'name' => 'Kabupaten Banjar', 'ibukota' => 'Martapura', 'k_bsni' => 'MTP'],
            ['id' => '343', 'provinsi_id' => '22', 'name' => 'Kabupaten Barito Kuala', 'ibukota' => 'Marabahan', 'k_bsni' => 'MRH'],
            ['id' => '344', 'provinsi_id' => '22', 'name' => 'Kabupaten Tapin', 'ibukota' => 'Rantau', 'k_bsni' => 'RTA'],
            ['id' => '345', 'provinsi_id' => '22', 'name' => 'Kabupaten Hulu Sungai Selatan', 'ibukota' => 'Kandangan', 'k_bsni' => 'KGN'],
            ['id' => '346', 'provinsi_id' => '22', 'name' => 'Kabupaten Hulu Sungai Tengah', 'ibukota' => 'Barabai', 'k_bsni' => 'BRB'],
            ['id' => '347', 'provinsi_id' => '22', 'name' => 'Kabupaten Hulu Sungai Utara', 'ibukota' => 'Amuntai', 'k_bsni' => 'AMT'],
            ['id' => '348', 'provinsi_id' => '22', 'name' => 'Kabupaten Tabalong', 'ibukota' => 'Tanjung', 'k_bsni' => 'TJG'],
            ['id' => '349', 'provinsi_id' => '22', 'name' => 'Kabupaten Tanah Bumbu', 'ibukota' => 'Batulicin', 'k_bsni' => 'BLN'],
            ['id' => '350', 'provinsi_id' => '22', 'name' => 'Kabupaten Balangan', 'ibukota' => 'Paringin', 'k_bsni' => 'PRN'],
            ['id' => '351', 'provinsi_id' => '22', 'name' => 'Kota Banjarmasin', 'ibukota' => 'Banjarmasin', 'k_bsni' => 'BJM'],
            ['id' => '352', 'provinsi_id' => '22', 'name' => 'Kota Banjarbaru', 'ibukota' => 'Banjarbaru', 'k_bsni' => 'BJB'],
            ['id' => '353', 'provinsi_id' => '23', 'name' => 'Kabupaten Paser', 'ibukota' => 'Tanah Grogot', 'k_bsni' => 'TGT'],
            ['id' => '354', 'provinsi_id' => '23', 'name' => 'Kabupaten Kutai Kartanegara', 'ibukota' => 'Tenggarong', 'k_bsni' => 'TRG'],
            ['id' => '355', 'provinsi_id' => '23', 'name' => 'Kabupaten Berau', 'ibukota' => 'Tanjung Redeb', 'k_bsni' => 'TNR'],
            ['id' => '356', 'provinsi_id' => '23', 'name' => 'Kabupaten Kutai Barat', 'ibukota' => 'Sendawar', 'k_bsni' => 'SDW'],
            ['id' => '357', 'provinsi_id' => '23', 'name' => 'Kabupaten Kutai Timur', 'ibukota' => 'Sanggatta', 'k_bsni' => 'SGT'],
            ['id' => '358', 'provinsi_id' => '23', 'name' => 'Kabupaten Penajam Paser Utara', 'ibukota' => 'Penajam', 'k_bsni' => 'PNJ'],
            ['id' => '359', 'provinsi_id' => '23', 'name' => 'Kota Balikpapan', 'ibukota' => 'Balikpapan', 'k_bsni' => 'BPP'],
            ['id' => '360', 'provinsi_id' => '23', 'name' => 'Kota Samarinda', 'ibukota' => 'Samarinda', 'k_bsni' => 'SMR'],
            ['id' => '361', 'provinsi_id' => '23', 'name' => 'Kota Bontang', 'ibukota' => 'Bontang', 'k_bsni' => 'BON'],
            ['id' => '362', 'provinsi_id' => '24', 'name' => 'Kabupaten Nunukan', 'ibukota' => 'Nunukan', 'k_bsni' => 'NNK'],
            ['id' => '363', 'provinsi_id' => '24', 'name' => 'Kabupaten Malinau', 'ibukota' => 'Malinau', 'k_bsni' => 'MLN'],
            ['id' => '364', 'provinsi_id' => '24', 'name' => 'Kabupaten Bulungan (Bulongan)', 'ibukota' => 'Tanjung Selor', 'k_bsni' => 'TJS'],
            ['id' => '365', 'provinsi_id' => '24', 'name' => 'Kabupaten Tana Tidung', 'ibukota' => 'Tideng Pale', 'k_bsni' => 'TDP'],
            ['id' => '366', 'provinsi_id' => '24', 'name' => 'Kota Tarakan', 'ibukota' => 'Tarakan', 'k_bsni' => 'TAR'],
            ['id' => '367', 'provinsi_id' => '25', 'name' => 'Kabupaten Bolaang Mongondow', 'ibukota' => 'Lolak', 'k_bsni' => 'LLK'],
            ['id' => '368', 'provinsi_id' => '25', 'name' => 'Kabupaten Minahasa', 'ibukota' => 'Tondano', 'k_bsni' => 'TNN'],
            ['id' => '369', 'provinsi_id' => '25', 'name' => 'Kabupaten Kepulauan Sangihe', 'ibukota' => 'Tahuna', 'k_bsni' => 'THN'],
            ['id' => '370', 'provinsi_id' => '25', 'name' => 'Kabupaten Kepulauan Talaud', 'ibukota' => 'Melongguane', 'k_bsni' => 'MGN'],
            ['id' => '371', 'provinsi_id' => '25', 'name' => 'Kabupaten Minahasa Selatan', 'ibukota' => 'Amurang', 'k_bsni' => 'AMR'],
            ['id' => '372', 'provinsi_id' => '25', 'name' => 'Kabupaten Minahasa Utara', 'ibukota' => 'Air Madidi', 'k_bsni' => 'ARM'],
            ['id' => '373', 'provinsi_id' => '25', 'name' => 'Kabupaten Minahasa Tenggara', 'ibukota' => 'Ratahan', 'k_bsni' => 'RTN'],
            ['id' => '374', 'provinsi_id' => '25', 'name' => 'Kabupaten Bolaang Mongondow Utara', 'ibukota' => 'Boroko', 'k_bsni' => 'BRK'],
            ['id' => '375', 'provinsi_id' => '25', 'name' => 'Kabupaten Kepulauan Siau Tagulandang Biaro (Sitaro)', 'ibukota' => 'Ondong Siau', 'k_bsni' => 'ODS'],
            ['id' => '376', 'provinsi_id' => '25', 'name' => 'Kabupaten Bolaang Mongondow Timur', 'ibukota' => 'Tutuyan', 'k_bsni' => 'TTY'],
            ['id' => '377', 'provinsi_id' => '25', 'name' => 'Kabupaten Bolaang Mongondow Selatan', 'ibukota' => 'Bolaang Uki', 'k_bsni' => 'BLU'],
            ['id' => '378', 'provinsi_id' => '25', 'name' => 'Kota Manado', 'ibukota' => 'Manado', 'k_bsni' => 'MND'],
            ['id' => '379', 'provinsi_id' => '25', 'name' => 'Kota Bitung', 'ibukota' => 'Bitung', 'k_bsni' => 'BIT'],
            ['id' => '380', 'provinsi_id' => '25', 'name' => 'Kota Tomohon', 'ibukota' => 'Tomohon', 'k_bsni' => 'TMH'],
            ['id' => '381', 'provinsi_id' => '25', 'name' => 'Kota Kotamobagu', 'ibukota' => 'Kotamobagu', 'k_bsni' => 'KTG'],
            ['id' => '382', 'provinsi_id' => '26', 'name' => 'Kabupaten Banggai', 'ibukota' => 'Luwuk', 'k_bsni' => 'LWK'],
            ['id' => '383', 'provinsi_id' => '26', 'name' => 'Kabupaten Poso', 'ibukota' => 'Poso', 'k_bsni' => 'PSO'],
            ['id' => '384', 'provinsi_id' => '26', 'name' => 'Kabupaten Donggala', 'ibukota' => 'Donggala', 'k_bsni' => 'DGL'],
            ['id' => '385', 'provinsi_id' => '26', 'name' => 'Kabupaten Toli-Toli', 'ibukota' => 'Toli Toli', 'k_bsni' => 'TLI'],
            ['id' => '386', 'provinsi_id' => '26', 'name' => 'Kabupaten Buol', 'ibukota' => 'Buol', 'k_bsni' => 'BUL'],
            ['id' => '387', 'provinsi_id' => '26', 'name' => 'Kabupaten Morowali', 'ibukota' => 'Bungku', 'k_bsni' => 'BGK'],
            ['id' => '388', 'provinsi_id' => '26', 'name' => 'Kabupaten Banggai Kepulauan', 'ibukota' => 'Salakan', 'k_bsni' => 'SKN'],
            ['id' => '389', 'provinsi_id' => '26', 'name' => 'Kabupaten Parigi Moutong', 'ibukota' => 'Parigi', 'k_bsni' => 'PRG'],
            ['id' => '390', 'provinsi_id' => '26', 'name' => 'Kabupaten Tojo Una-Una', 'ibukota' => 'Ampana', 'k_bsni' => 'APN'],
            ['id' => '391', 'provinsi_id' => '26', 'name' => 'Kabupaten Sigi', 'ibukota' => 'Sigi Biromaru', 'k_bsni' => 'SGB'],
            ['id' => '392', 'provinsi_id' => '26', 'name' => 'Kota Palu', 'ibukota' => 'Palu', 'k_bsni' => 'PAL'],
            ['id' => '393', 'provinsi_id' => '27', 'name' => 'Kabupaten Selayar (Kepulauan Selayar)', 'ibukota' => 'Benteng', 'k_bsni' => 'BEN'],
            ['id' => '394', 'provinsi_id' => '27', 'name' => 'Kabupaten Bulukumba', 'ibukota' => 'Bulukumba', 'k_bsni' => 'BLK'],
            ['id' => '395', 'provinsi_id' => '27', 'name' => 'Kabupaten Bantaeng', 'ibukota' => 'Bantaeng', 'k_bsni' => 'BAN'],
            ['id' => '396', 'provinsi_id' => '27', 'name' => 'Kabupaten Jeneponto', 'ibukota' => 'Jeneponto', 'k_bsni' => 'JNP'],
            ['id' => '397', 'provinsi_id' => '27', 'name' => 'Kabupaten Takalar', 'ibukota' => 'Takalar', 'k_bsni' => 'TKA'],
            ['id' => '398', 'provinsi_id' => '27', 'name' => 'Kabupaten Gowa', 'ibukota' => 'Sungguminasa', 'k_bsni' => 'SGM'],
            ['id' => '399', 'provinsi_id' => '27', 'name' => 'Kabupaten Sinjai', 'ibukota' => 'Sinjai', 'k_bsni' => 'SNJ'],
            ['id' => '400', 'provinsi_id' => '27', 'name' => 'Kabupaten Bone', 'ibukota' => 'Watampone', 'k_bsni' => 'WTP'],
            ['id' => '401', 'provinsi_id' => '27', 'name' => 'Kabupaten Maros', 'ibukota' => 'Maros', 'k_bsni' => 'MRS'],
            ['id' => '402', 'provinsi_id' => '27', 'name' => 'Kabupaten Pangkajene Kepulauan', 'ibukota' => 'Pangkajene', 'k_bsni' => 'PKJ'],
            ['id' => '403', 'provinsi_id' => '27', 'name' => 'Kabupaten Barru', 'ibukota' => 'Barru', 'k_bsni' => 'BAR'],
            ['id' => '404', 'provinsi_id' => '27', 'name' => 'Kabupaten Soppeng', 'ibukota' => 'Watan Soppeng', 'k_bsni' => 'WNS'],
            ['id' => '405', 'provinsi_id' => '27', 'name' => 'Kabupaten Wajo', 'ibukota' => 'Sengkang', 'k_bsni' => 'SKG'],
            ['id' => '406', 'provinsi_id' => '27', 'name' => 'Kabupaten Sidenreng Rappang (Sidrap)', 'ibukota' => 'Sidenreng', 'k_bsni' => 'SDR'],
            ['id' => '407', 'provinsi_id' => '27', 'name' => 'Kabupaten Pinrang', 'ibukota' => 'Pinrang', 'k_bsni' => 'PIN'],
            ['id' => '408', 'provinsi_id' => '27', 'name' => 'Kabupaten Enrekang', 'ibukota' => 'Enrekang', 'k_bsni' => 'ENR'],
            ['id' => '409', 'provinsi_id' => '27', 'name' => 'Kabupaten Luwu', 'ibukota' => 'Palopo', 'k_bsni' => 'PLP'],
            ['id' => '410', 'provinsi_id' => '27', 'name' => 'Kabupaten Tana Toraja', 'ibukota' => 'Makale', 'k_bsni' => 'MAK'],
            ['id' => '411', 'provinsi_id' => '27', 'name' => 'Kabupaten Luwu Utara', 'ibukota' => 'Masamba', 'k_bsni' => 'MSB'],
            ['id' => '412', 'provinsi_id' => '27', 'name' => 'Kabupaten Luwu Timur', 'ibukota' => 'Malili', 'k_bsni' => 'MLL'],
            ['id' => '413', 'provinsi_id' => '27', 'name' => 'Kabupaten Toraja Utara', 'ibukota' => 'Rantepao', 'k_bsni' => 'RTP'],
            ['id' => '414', 'provinsi_id' => '27', 'name' => 'Kota Makassar', 'ibukota' => 'Makassar', 'k_bsni' => 'MKS'],
            ['id' => '415', 'provinsi_id' => '27', 'name' => 'Kota Parepare', 'ibukota' => 'Pare Pare', 'k_bsni' => 'PRE'],
            ['id' => '416', 'provinsi_id' => '27', 'name' => 'Kota Palopo', 'ibukota' => 'Palopo', 'k_bsni' => 'PLP'],
            ['id' => '417', 'provinsi_id' => '28', 'name' => 'Kabupaten Kolaka', 'ibukota' => 'Kolaka', 'k_bsni' => 'KKA'],
            ['id' => '418', 'provinsi_id' => '28', 'name' => 'Kabupaten Konawe', 'ibukota' => 'Unaaha', 'k_bsni' => 'UNH'],
            ['id' => '419', 'provinsi_id' => '28', 'name' => 'Kabupaten Muna', 'ibukota' => 'Raha', 'k_bsni' => 'RAH'],
            ['id' => '420', 'provinsi_id' => '28', 'name' => 'Kabupaten Buton', 'ibukota' => 'Pasar Wajo', 'k_bsni' => 'PSW'],
            ['id' => '421', 'provinsi_id' => '28', 'name' => 'Kabupaten Konawe Selatan', 'ibukota' => 'Andoolo', 'k_bsni' => 'ADL'],
            ['id' => '422', 'provinsi_id' => '28', 'name' => 'Kabupaten Bombana', 'ibukota' => 'Rumbia', 'k_bsni' => 'RMB'],
            ['id' => '423', 'provinsi_id' => '28', 'name' => 'Kabupaten Wakatobi', 'ibukota' => 'Wangi Wangi', 'k_bsni' => 'WGW'],
            ['id' => '424', 'provinsi_id' => '28', 'name' => 'Kabupaten Kolaka Utara', 'ibukota' => 'Lasusua', 'k_bsni' => 'LSS'],
            ['id' => '425', 'provinsi_id' => '28', 'name' => 'Kabupaten Konawe Utara', 'ibukota' => 'Wanggudu', 'k_bsni' => 'WGD'],
            ['id' => '426', 'provinsi_id' => '28', 'name' => 'Kabupaten Buton Utara', 'ibukota' => 'Buranga', 'k_bsni' => 'BNG'],
            ['id' => '427', 'provinsi_id' => '28', 'name' => 'Kota Kendari', 'ibukota' => 'Kendari', 'k_bsni' => 'KDI'],
            ['id' => '428', 'provinsi_id' => '28', 'name' => 'Kota Bau Bau', 'ibukota' => 'Bau-Bau', 'k_bsni' => 'BAU'],
            ['id' => '429', 'provinsi_id' => '29', 'name' => 'Kabupaten Gorontalo', 'ibukota' => 'Gorontalo', 'k_bsni' => 'GTO'],
            ['id' => '430', 'provinsi_id' => '29', 'name' => 'Kabupaten Boalemo', 'ibukota' => 'Tilamuta', 'k_bsni' => 'TMT'],
            ['id' => '431', 'provinsi_id' => '29', 'name' => 'Kabupaten Bone Bolango', 'ibukota' => 'Suwawa', 'k_bsni' => 'SWW'],
            ['id' => '432', 'provinsi_id' => '29', 'name' => 'Kabupaten Pahuwato (Pohowato)', 'ibukota' => 'Marisa', 'k_bsni' => 'MAR'],
            ['id' => '433', 'provinsi_id' => '29', 'name' => 'Kabupaten Gorontalo Utara', 'ibukota' => 'Kwandang', 'k_bsni' => 'KWD'],
            ['id' => '434', 'provinsi_id' => '29', 'name' => 'Kota Gorontalo', 'ibukota' => 'Gorontalo', 'k_bsni' => 'GTO'],
            ['id' => '435', 'provinsi_id' => '30', 'name' => 'Kabupaten Mamuju Utara', 'ibukota' => 'Pasangkayu', 'k_bsni' => 'PKY'],
            ['id' => '436', 'provinsi_id' => '30', 'name' => 'Kabupaten Mamuju', 'ibukota' => 'Mamuju', 'k_bsni' => 'MAM'],
            ['id' => '437', 'provinsi_id' => '30', 'name' => 'Kabupaten Mamasa', 'ibukota' => 'Mamasa', 'k_bsni' => 'MMS'],
            ['id' => '438', 'provinsi_id' => '30', 'name' => 'Kabupaten Polewali Mandar', 'ibukota' => 'Polewali', 'k_bsni' => 'PLW'],
            ['id' => '439', 'provinsi_id' => '30', 'name' => 'Kabupaten Majene', 'ibukota' => 'Majene', 'k_bsni' => 'MJN'],
            ['id' => '440', 'provinsi_id' => '31', 'name' => 'Kabupaten Maluku Tengah', 'ibukota' => 'Masohi', 'k_bsni' => 'MSH'],
            ['id' => '441', 'provinsi_id' => '31', 'name' => 'Kabupaten Maluku Tenggara', 'ibukota' => 'Tual', 'k_bsni' => 'TUL'],
            ['id' => '442', 'provinsi_id' => '31', 'name' => 'Kabupaten Maluku Tenggara Barat', 'ibukota' => 'Saumlaki', 'k_bsni' => 'SML'],
            ['id' => '443', 'provinsi_id' => '31', 'name' => 'Kabupaten Buru', 'ibukota' => 'Namlea', 'k_bsni' => 'NLA'],
            ['id' => '444', 'provinsi_id' => '31', 'name' => 'Kabupaten Seram Bagian Timur', 'ibukota' => 'Dataran Hunimoa', 'k_bsni' => 'DTH'],
            ['id' => '445', 'provinsi_id' => '31', 'name' => 'Kabupaten Seram Bagian Barat', 'ibukota' => 'Dataran Hunipopu', 'k_bsni' => 'DRH'],
            ['id' => '446', 'provinsi_id' => '31', 'name' => 'Kabupaten Kepulauan Aru', 'ibukota' => 'Dobo', 'k_bsni' => 'DOB'],
            ['id' => '447', 'provinsi_id' => '31', 'name' => 'Kabupaten Maluku Barat Daya', 'ibukota' => 'Tiakur', 'k_bsni' => 'TKR'],
            ['id' => '448', 'provinsi_id' => '31', 'name' => 'Kabupaten Buru Selatan', 'ibukota' => 'Namrole', 'k_bsni' => 'NMR'],
            ['id' => '449', 'provinsi_id' => '31', 'name' => 'Kota Ambon', 'ibukota' => 'Ambon', 'k_bsni' => 'AMB'],
            ['id' => '450', 'provinsi_id' => '31', 'name' => 'Kota Tual', 'ibukota' => 'Tual', 'k_bsni' => 'TUL'],
            ['id' => '451', 'provinsi_id' => '32', 'name' => 'Kabupaten Halmahera Barat', 'ibukota' => 'Jailolo', 'k_bsni' => 'JLL'],
            ['id' => '452', 'provinsi_id' => '32', 'name' => 'Kabupaten Halmahera Tengah', 'ibukota' => 'Weda', 'k_bsni' => 'WED'],
            ['id' => '453', 'provinsi_id' => '32', 'name' => 'Kabupaten Halmahera Utara', 'ibukota' => 'Tobelo', 'k_bsni' => 'TOB'],
            ['id' => '454', 'provinsi_id' => '32', 'name' => 'Kabupaten Halmahera Selatan', 'ibukota' => 'Labuha', 'k_bsni' => 'LBA'],
            ['id' => '455', 'provinsi_id' => '32', 'name' => 'Kabupaten Kepulauan Sula', 'ibukota' => 'Sanana', 'k_bsni' => 'SNN'],
            ['id' => '456', 'provinsi_id' => '32', 'name' => 'Kabupaten Halmahera Timur', 'ibukota' => 'Maba', 'k_bsni' => 'MAB'],
            ['id' => '457', 'provinsi_id' => '32', 'name' => 'Kabupaten Pulau Morotai', 'ibukota' => 'Morotai Selatan', 'k_bsni' => 'MTS'],
            ['id' => '458', 'provinsi_id' => '32', 'name' => 'Kota Ternate', 'ibukota' => 'Ternate', 'k_bsni' => 'TTE'],
            ['id' => '459', 'provinsi_id' => '32', 'name' => 'Kota Tidore Kepulauan', 'ibukota' => 'Tidore', 'k_bsni' => 'TDR'],
            ['id' => '460', 'provinsi_id' => '33', 'name' => 'Kabupaten Merauke', 'ibukota' => 'Merauke', 'k_bsni' => 'MRK'],
            ['id' => '461', 'provinsi_id' => '33', 'name' => 'Kabupaten Jayawijaya', 'ibukota' => 'Wamena', 'k_bsni' => 'WAM'],
            ['id' => '462', 'provinsi_id' => '33', 'name' => 'Kabupaten Jayapura', 'ibukota' => 'Jayapura', 'k_bsni' => 'JAP'],
            ['id' => '463', 'provinsi_id' => '33', 'name' => 'Kabupaten Nabire', 'ibukota' => 'Nabire', 'k_bsni' => 'NAB'],
            ['id' => '464', 'provinsi_id' => '33', 'name' => 'Kabupaten Kepulauan Yapen (Yapen Waropen)', 'ibukota' => 'Serui', 'k_bsni' => 'SRU'],
            ['id' => '465', 'provinsi_id' => '33', 'name' => 'Kabupaten Biak Numfor', 'ibukota' => 'Biak', 'k_bsni' => 'BIK'],
            ['id' => '466', 'provinsi_id' => '33', 'name' => 'Kabupaten Puncak Jaya', 'ibukota' => 'Mulia', 'k_bsni' => 'MUL'],
            ['id' => '467', 'provinsi_id' => '33', 'name' => 'Kabupaten Paniai', 'ibukota' => 'Enarotali', 'k_bsni' => 'ERT'],
            ['id' => '468', 'provinsi_id' => '33', 'name' => 'Kabupaten Mimika', 'ibukota' => 'Timika', 'k_bsni' => 'TIM'],
            ['id' => '469', 'provinsi_id' => '33', 'name' => 'Kabupaten Sarmi', 'ibukota' => 'Sarmi', 'k_bsni' => 'SMI'],
            ['id' => '470', 'provinsi_id' => '33', 'name' => 'Kabupaten Keerom', 'ibukota' => 'Waris', 'k_bsni' => 'WRS'],
            ['id' => '471', 'provinsi_id' => '33', 'name' => 'Kabupaten Pegunungan Bintang', 'ibukota' => 'Oksibil', 'k_bsni' => 'OSB'],
            ['id' => '472', 'provinsi_id' => '33', 'name' => 'Kabupaten Yahukimo', 'ibukota' => 'Sumohai', 'k_bsni' => 'SMH'],
            ['id' => '473', 'provinsi_id' => '33', 'name' => 'Kabupaten Tolikara', 'ibukota' => 'Karubaga', 'k_bsni' => 'KBG'],
            ['id' => '474', 'provinsi_id' => '33', 'name' => 'Kabupaten Waropen', 'ibukota' => 'Botawa', 'k_bsni' => 'BTW'],
            ['id' => '475', 'provinsi_id' => '33', 'name' => 'Kabupaten Boven Digoel', 'ibukota' => 'Tanah Merah', 'k_bsni' => 'TMR'],
            ['id' => '476', 'provinsi_id' => '33', 'name' => 'Kabupaten Mappi', 'ibukota' => 'Kepi', 'k_bsni' => 'KEP'],
            ['id' => '477', 'provinsi_id' => '33', 'name' => 'Kabupaten Asmat', 'ibukota' => 'Agats', 'k_bsni' => 'AGT'],
            ['id' => '478', 'provinsi_id' => '33', 'name' => 'Kabupaten Supiori', 'ibukota' => 'Sorendiweri', 'k_bsni' => 'SRW'],
            ['id' => '479', 'provinsi_id' => '33', 'name' => 'Kabupaten Mamberamo Raya', 'ibukota' => 'Burmeso', 'k_bsni' => 'BRM'],
            ['id' => '480', 'provinsi_id' => '33', 'name' => 'Kabupaten Mamberamo Tengah', 'ibukota' => 'Kobakma', 'k_bsni' => 'KBK'],
            ['id' => '481', 'provinsi_id' => '33', 'name' => 'Kabupaten Yalimo', 'ibukota' => 'Elelim', 'k_bsni' => 'ELL'],
            ['id' => '482', 'provinsi_id' => '33', 'name' => 'Kabupaten Lanny Jaya', 'ibukota' => 'Tiom', 'k_bsni' => 'TOM'],
            ['id' => '483', 'provinsi_id' => '33', 'name' => 'Kabupaten Nduga', 'ibukota' => 'Kenyam', 'k_bsni' => 'KYM'],
            ['id' => '484', 'provinsi_id' => '33', 'name' => 'Kabupaten Puncak', 'ibukota' => 'Ilaga', 'k_bsni' => 'ILG'],
            ['id' => '485', 'provinsi_id' => '33', 'name' => 'Kabupaten Dogiyai', 'ibukota' => 'Kigamani', 'k_bsni' => 'KGM'],
            ['id' => '486', 'provinsi_id' => '33', 'name' => 'Kabupaten Intan Jaya', 'ibukota' => 'Sugapa', 'k_bsni' => 'SGP'],
            ['id' => '487', 'provinsi_id' => '33', 'name' => 'Kabupaten Deiyai (Deliyai)', 'ibukota' => 'Tigi', 'k_bsni' => 'TIG'],
            ['id' => '488', 'provinsi_id' => '33', 'name' => 'Kota Jayapura', 'ibukota' => 'Jayapura', 'k_bsni' => 'JAP'],
            ['id' => '489', 'provinsi_id' => '34', 'name' => 'Kabupaten Sorong', 'ibukota' => 'Aimas', 'k_bsni' => 'AMS'],
            ['id' => '490', 'provinsi_id' => '34', 'name' => 'Kabupaten Manokwari', 'ibukota' => 'Manokwari', 'k_bsni' => 'MNK'],
            ['id' => '491', 'provinsi_id' => '34', 'name' => 'Kabupaten Fakfak', 'ibukota' => 'Fak Fak', 'k_bsni' => 'FFK'],
            ['id' => '492', 'provinsi_id' => '34', 'name' => 'Kabupaten Sorong Selatan', 'ibukota' => 'Teminabuan', 'k_bsni' => 'TMB'],
            ['id' => '493', 'provinsi_id' => '34', 'name' => 'Kabupaten Raja Ampat', 'ibukota' => 'Waisai', 'k_bsni' => 'WAS'],
            ['id' => '494', 'provinsi_id' => '34', 'name' => 'Kabupaten Teluk Bintuni', 'ibukota' => 'Bintuni', 'k_bsni' => 'BTI'],
            ['id' => '495', 'provinsi_id' => '34', 'name' => 'Kabupaten Teluk Wondama', 'ibukota' => 'Rasiei', 'k_bsni' => 'RAS'],
            ['id' => '496', 'provinsi_id' => '34', 'name' => 'Kabupaten Kaimana', 'ibukota' => 'Kaimana', 'k_bsni' => 'KMN'],
            ['id' => '497', 'provinsi_id' => '34', 'name' => 'Kabupaten Tambrauw', 'ibukota' => 'Fef', 'k_bsni' => 'FEF'],
            ['id' => '498', 'provinsi_id' => '34', 'name' => 'Kabupaten Maybrat', 'ibukota' => 'Aifat', 'k_bsni' => 'AFT'],
            ['id' => '499', 'provinsi_id' => '34', 'name' => 'Kabupaten Pegunungan Arfak', 'ibukota' => 'Anggi', 'k_bsni' => 'ANG'],
            ['id' => '500', 'provinsi_id' => '34', 'name' => 'Kabupaten Manokwari Selatan', 'ibukota' => 'Ransiki', 'k_bsni' => 'RNK'],
            ['id' => '501', 'provinsi_id' => '34', 'name' => 'Kota Sorong', 'ibukota' => 'Sorong', 'k_bsni' => 'SON']
        ];
        foreach ($wilayah_kabupaten as $a => $b) {
            \App\Models\Kabupaten::firstOrCreate(
                ['name' => $b['name'], 'ibukota' => $b['ibukota'], 'k_bsni' => $b['k_bsni'], 'provinsi_id' => $b['provinsi_id']],
                ['name' => $b['name'], 'ibukota' => $b['ibukota'], 'k_bsni' => $b['k_bsni'], 'provinsi_id' => $b['provinsi_id']]
            );
            $this->command->warn("Data wilayah_kabupaten, " . $b['name'] . " " .  $b['id'] . ".");
        }
    }
}
